# frontend/Dockerfile.dev
FROM node:20

WORKDIR /front

# ここを必ず `RUN pnpm install` の前に書く
ENV ROLLUP_NO_BINARY=true

RUN corepack enable
COPY package.json pnpm-lock.yaml* ./
RUN pnpm install --frozen-lockfile
COPY . .

CMD ["pnpm", "run", "dev", "--host"]
