version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: fequiz
      POSTGRES_USER: feuser
      POSTGRES_PASSWORD: fepass
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    env_file: ./backend/.env
    environment:
      DATABASE_URL: postgres://feuser:fepass@db:5432/fequiz
    volumes:
      - ./backend:/app      # ホットリロード用マウント
      - ./backend/data:/data
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  front_dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/front
      - frontend_node_modules:/front/node_modules 
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db_data:
  frontend_node_modules:
