# Generated by Django 4.2.20 on 2025-04-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='exam_part',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='question',
            name='exam_year',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(default='unknown', max_length=32),
        ),
    ]
