# Generated by Django 4.2.20 on 2025-04-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='問題文')),
                ('choice_a', models.CharField(max_length=255, verbose_name='選択肢 A')),
                ('choice_b', models.CharField(max_length=255, verbose_name='選択肢 B')),
                ('choice_c', models.CharField(max_length=255, verbose_name='選択肢 C')),
                ('choice_d', models.CharField(max_length=255, verbose_name='選択肢 D')),
                ('correct', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1, verbose_name='正解')),
                ('category', models.CharField(choices=[('tech', 'テクノロジ系'), ('mgmt', 'マネジメント系'), ('strat', 'ストラテジ系')], default='tech', max_length=5, verbose_name='分野')),
            ],
        ),
    ]
