# Generated by Django 4.2.20 on 2025-05-05 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0004_alter_question_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='guess',
            new_name='user_answer',
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
