# Generated by Django 4.2.20 on 2025-05-05 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_rename_guess_answer_user_answer_alter_answer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='user_answer',
            new_name='guess',
        ),
    ]
